### ISSUE TITLE
Valkyrie RemoteCommunication GID error

### ISSUE THREAD

**Issue by zars15** [CrescentCode/ValkyrieFramework#42]
Both dev and bleeding-edge branches fail to initialize with the following error:

`20:46:45.543 - Model.MainModule.Core.Components.RemoteCommunication:54: This GID does not have any permissions set, or does not exist!`

The game ID seems to be correct and matching. Same GID and secret code worked just fine on Gskartwii/ValkyrieFramework/bleeding-edge branch.

**Comment by Gskartwii** [comment]
This is due to server-side issue that I've been unable to reproduce. Regardless, it should be fixed now.

**Comment by zars15** [comment]
The issue still persists. Published place shows same error as well. 

Perhaps Valkyrie should be allowed to boot even on failed game authentication? So that you could still have game working, but with some limitations.

**Comment by Gskartwii** [comment]
Valkyrie should be able to boot without authentication in Studio test servers.

I'll try fixing the issue again tomorrow. I'm going to need to know the game ID but *not* the key to fix it.

**Comment by zars15** [comment]
Test server does work fine without authentication, but not solo or online server.

The game ID: zarsbranchkin.redpulse

I had tried creating other game ID, with simpler key, but I still had the same problem.

**Comment by Gskartwii** [comment]
That indeed was a bug but not related to this. `game.etlua` is only used for handling the displaying of /game/*. Also, adding achievements through the site or deleting games is not implemented yet.

I think is because of my text editor adding trailing newlines to the permission file. I've attempted a fix again.

**Comment by zars15** [comment]
Play solo and test server doesn't throw the error anymore on official bleeding-edge branch. Published place still errors, but with different error now:

`Model.MainModule.Core.Components.RemoteCommunication:54: Invalid UID-CoKey-GID combination!`

**Comment by Gskartwii** [comment]
You've hit a server bug again (I'm sorry). I should have fixed that now.

**Comment by zars15** [comment]
Everything seems to work fine now, thanks!

**Comment by Gskartwii** [comment]
You're welcome! Thanks for reporting the bugs and please do keep on doing so if you find any more.
